apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pubnats-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pubnats
      labels:
        app: pubnats
    spec:
      containers:
      - name: pubnats
        imagePullPolicy: Always
        image: shocnt/publish-nats:latest
        env:
        - name: TOPIC
          value: nutanix
        command:
        - sh
        - -c
        - "exec python3 main.py"
