apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: subnats-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: subnats
      labels:
        app: subnats
    spec:
      containers:
      - name: subnats
        imagePullPolicy: Always
        image: shocnt/subnats:latest
        env:
        - name: TOPIC
          value: shuchida-dp-nats-in
        command:
        - sh
        - -c
        - "exec python3 main.py"
